name = "DTWDT.jl"
uuid = "19e40bf2-84a3-11e9-2673-673833aa2bdc"
authors = ["kurama"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
